---
# vars file for roles/socks-synwall
dante:
  url: "https://www.inet.no/dante/files"
  checksum: "4c97cff23e5c9b00ca1ec8a95ab22972813921d7fbf60fc453e3e06382fc38a7"
  checksum_alg: "sha256"
  version: "1.4.2"
  download_dir: "/opt"
  conf:
    path: "/etc/dante.conf"
    log_path: "/var/log/danted.log"
    interface: "enp0s3"

luks:
  volgroup: "modprobe"
  logicalvol: "modprobe"
  name: "modprobe"
  mount_point: "/etc/modprobe.d"
  fstype: "ext4"

syngate:
  module_dir: "/lib/modules/{{ ansible_kernel }}/extra/"
  repo: "git@wecode.sorint.it:cpizzi/SYNwall.git"
  path: "/opt/SYNwall/"
  params:
    dstnet_list: "10.0.0.0/8"
    # Pre-Shared Key used for the OneTimePassword
    psk_list: "qazwsxedcrfvtgbyhnujmikolpqazwsx"
    # Time precision parameter
    precision_list: 1
    # Enable IP Spoofing protection
    enable_antispoof_list: 0
    # Enable OTP for UDP protocol list
    enable_udp_list: 0
